### ISSUE TITLE
装备属性展示缺失补充

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/item#7]
装备会效不显示https://www.jx3box.com/item/#/view/8_32007

**Comment by Kaviilee** [comment]
![image](https://user-images.githubusercontent.com/25825282/147376730-250dbcaf-73ea-4156-ace3-f898333a400c.png)

https://helper.jx3box.com/api/item/8_32007 接口缺少会效字段

@kuguats

**Comment by x3zvawq** [comment]
该问题是数据库建库设计问题，jx3box_helper内的helper_item_attributes表的type字段是varchar类型，并且最大长度被设置为30
会效属性是atPhysicsCriticalDamagePowerBase长度是32，所以可能当初写入的时候被截断成了atPhysicsCriticalDamagePowerBa
后端在处理数据的时候不知道该物品有会效（x
要解决问题的话可以alter一下这个表，然后跑一个批量替换的脚本应该就行了

**Comment by iRuxu** [comment]
目前数据库已修正。

接口暂时仍为返回，是否为缓存。

![image](https://user-images.githubusercontent.com/8476969/156922125-ca033dff-ff30-4498-b87e-f8acd0e342f1.png)

**Comment by iRuxu** [comment]
后端已将该字段改为255，php模型注意同步。

**Comment by blankqwq** [comment]
数据库还需要更新一下type 依据下面这个写个update

> 该问题是数据库建库设计问题，jx3box_helper内的helper_item_attributes表的type字段是varchar类型，并且最大长度被设置为30 会效属性是atPhysicsCriticalDamagePowerBase长度是32，所以可能当初写入的时候被截断成了atPhysicsCriticalDamagePowerBa 后端在处理数据的时候不知道该物品有会效（x 要解决问题的话可以alter一下这个表，然后跑一个批量替换的脚本应该就行了

**Comment by iRuxu** [comment]
最终确认，需要苦瓜重新构建数据库数据。
![image](https://user-images.githubusercontent.com/8476969/156923143-6bc931c4-3751-4a08-ad66-731ace585638.png)

**Comment by iRuxu** [comment]
![image](https://user-images.githubusercontent.com/8476969/156932747-c00a022e-a989-4588-9292-e51bf0122fc2.png)
